# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'


use_frameworks!

target 'GZTracking' do

pod 'Mixpanel'
pod 'FBSDKCoreKit', '4.6.0-beta1'

end

target 'GZTrackingSystemTests' do

end

