# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

use_frameworks!

target 'Example' do
pod 'GZTracking', :git => 'https://github.com/gradyzhuo/GZTracking'
end

target 'ExampleTests' do

end

target 'ExampleUITests' do

end

